### ISSUE TITLE
Lag in update from homebase and earning

### ISSUE THREAD

**Issue by pgg1309** [OpportunityInsights/EconomicTracker#1]
Hello. First congrats on the excellent job of putting all this info together in a very user friendly way.

I would like to know why such a delay in getting information from *Homebase* and *Earning* databases. I am aware they release their info for non paying clients with a two-week delay, but the information in this page is older than that.

Thanks.

**Comment by michaelstepner** [comment]
Hi @pgg1309, we're working through some data processing and data transfer issues with the most recent weeks of Earnin data. We hope to have an update in about a week.
