### ISSUE TITLE
"imputed_from_cz" meaning in Zearn data

### ISSUE THREAD

**Issue by wtorous** [OpportunityInsights/EconomicTracker#2]
What does this binary indicator mean in the Zearn dataset?

**Comment by michaelstepner** [comment]
Hi @wtorousa, apologies that I didn't get to this issue earlier! The answer to your question is now incorporated into the Data Documentation that we posted today: https://github.com/OpportunityInsights/EconomicTracker/blob/main/docs/oi_tracker_data_documentation.md#online-math-participation

> To ensure privacy, the data we obtain are masked such that any county with fewer than two districts, fewer than three schools, or fewer than 50 students on average using Zearn Math is excluded. Where possible, masked county levels values are replaced by commuting zone means.
