### ISSUE TITLE
Low Inc Emp All Businesses / Low Inc Emp Small Businesses

### ISSUE THREAD

**Issue by ECONDATA** [OpportunityInsights/EconomicTracker#3]
Hi there,

Thanks for sharing the data! 

For the Low Inc Emp All Businesses / Low Inc Emp Small Businesses data description. You may want to correct the description for the emp_inchigh. It's the same description for emp_incmiddle.

emp_incmiddle: Employment level for workers in the middle two quartiles of the national income distribution.
emp_inchigh: Employment level for workers in the middle two quartiles of the national income distribution.

Thanks!

**Comment by michaelstepner** [comment]
Thanks for the heads up @ECONDATA! I've fixed this issue in the commit referenced above.
