### ISSUE TITLE
Replicating paper figures

### ISSUE THREAD

**Issue by sterlinm** [OpportunityInsights/EconomicTracker#6]
It's not possible to replicate the figures comparing Affinity to MRTS (1b and 1c) in the [paper](https://opportunityinsights.org/wp-content/uploads/2020/05/tracker_paper.pdf) from the publicly available data, is it? Thanks!

**Comment by michaelstepner** [comment]
We're working on ensuring every figure is replicable from the publicly available data and posting code to do so. If you check back in a couple weeks, that should be up!

**Comment by sterlinm** [comment]
Awesome thanks!
