### ISSUE TITLE
Economic Data Changes

### ISSUE THREAD

**Issue by steveriano** [OpportunityInsights/EconomicTracker#7]
Hi,

I see that the earlier file structure of Low Inc Earnings / Low Inc Emp files has gone, and now there is a single, consolidated file for each of national/state/county/city with fewer fields included in the file. Is there any documentation of this transition? Am I right in thinking that the emp fields that are common to both formats are the same data?

Thanks!

**Comment by michaelstepner** [comment]
Hi Steve and Robert,

The change in format happened when we obtained new data from Paychex and Intuit that dramatically expanded the amount of data we have on employment trends. The previous `Low Inc Earnings` / `Low Inc Emp` datasets were derived from a mix of Earnin and Homebase data. The new low-income employment data in the `Combined Employment` series comes from a mix of Paychex, Earnin and Kronos, and provides a larger sample that is more representative across industries.

We provide an overview of the series sources and construction in our new [Data Documentation](https://github.com/OpportunityInsights/EconomicTracker/blob/main/docs/oi_tracker_data_documentation.md#employment), and additional detail in the [accompanying paper](https://opportunityinsights.org/wp-content/uploads/2020/05/tracker_paper.pdf).
