### ISSUE TITLE
Womply updates

### ISSUE THREAD

**Issue by c3-robertyoung** [OpportunityInsights/EconomicTracker#8]
Will you be updating the Womply Merchants and Revenue datasets moving forward? They haven't been updated since 8/21.

**Comment by michaelstepner** [comment]
Thanks for checking in, Robert. Womply changed the way they process their raw data at that time and we've been working to ensure the next Womply updates are reliable and complete. This week we posted up-to-date data from Womply without all the breakdowns that we used to have, and we are working with them on completing the missing breakdowns. I've added some detail to the Data Dictionary: https://github.com/OpportunityInsights/EconomicTracker/blob/main/docs/oi_tracker_data_dictionary.md#womply-merchants
