### ISSUE TITLE
Economic Tracker database- 2 questions - Affinity data and Earnings

### ISSUE THREAD

**Issue by trja111** [OpportunityInsights/EconomicTracker#9]
Hello @michaelstepner , 

We have found the Economic Tracker database to be a useful resource. Thank you for making it available. 

We have two quick questions pertaining the database:
-	Can the debit and credit card transaction data (from Affinity Solutions) currently available as an index  be made available in y/y growth or in level terms? This could be useful for cross-country comparisons.
-	Some time in the summer, we noticed you had earnings data for low income workers (under the mnemonic “pay”), yet we seem to be unable to find it now. We are looking for the data in GitHub.  Should we look somewhere else? Is it no longer available? 

Thanks in advance for your help, 
JT

**Comment by michaelstepner** [comment]
Hi JT,

Thanks for reaching out!

> Can the debit and credit card transaction data (from Affinity Solutions) currently available as an index be made available in y/y growth or in level terms? This could be useful for cross-country comparisons.

Our current data sharing agreement only permits us to share the data as indexed values relative to January 2020. In Figure 2 of [the paper](https://opportunityinsights.org/wp-content/uploads/2020/05/tracker_paper.pdf) we plot the changes in levels by using public data to set the level in January. Sorry we can't provide a more direct solution, but I hope that might work for your purpose.

> Some time in the summer, we noticed you had earnings data for low income workers (under the mnemonic “pay”), yet we seem to be unable to find it now. We are looking for the data in GitHub. Should we look somewhere else? Is it no longer available?

You can download the Low Income Earnings data by delving into the history of the Github repository: https://github.com/OpportunityInsights/EconomicTracker/tree/5f914ee4e71f56a33857b63e0bd07d71bc31e847/data

This data was released on June 17 and is based on a combination of information from Earnin and Homebase. Our latest data tracks employment for workers at various income levels and is based on data from Paychex, Intuit, Earnin and Kronos. This newer data is more comprehensive, but unfortunately we have not been able to measure earnings with the information we are currently receiving. I hope we'll be able to re-incorporate earnings in the future.

- - -

Best of luck with your work,
Michael
